// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package rule_group

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Capacity, b.ko.Spec.Capacity) {
		delta.Add("Spec.Capacity", a.ko.Spec.Capacity, b.ko.Spec.Capacity)
	} else if a.ko.Spec.Capacity != nil && b.ko.Spec.Capacity != nil {
		if *a.ko.Spec.Capacity != *b.ko.Spec.Capacity {
			delta.Add("Spec.Capacity", a.ko.Spec.Capacity, b.ko.Spec.Capacity)
		}
	}
	if len(a.ko.Spec.CustomResponseBodies) != len(b.ko.Spec.CustomResponseBodies) {
		delta.Add("Spec.CustomResponseBodies", a.ko.Spec.CustomResponseBodies, b.ko.Spec.CustomResponseBodies)
	} else if len(a.ko.Spec.CustomResponseBodies) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.CustomResponseBodies, b.ko.Spec.CustomResponseBodies) {
			delta.Add("Spec.CustomResponseBodies", a.ko.Spec.CustomResponseBodies, b.ko.Spec.CustomResponseBodies)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.Rules) != len(b.ko.Spec.Rules) {
		delta.Add("Spec.Rules", a.ko.Spec.Rules, b.ko.Spec.Rules)
	} else if len(a.ko.Spec.Rules) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.Rules, b.ko.Spec.Rules) {
			delta.Add("Spec.Rules", a.ko.Spec.Rules, b.ko.Spec.Rules)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Scope, b.ko.Spec.Scope) {
		delta.Add("Spec.Scope", a.ko.Spec.Scope, b.ko.Spec.Scope)
	} else if a.ko.Spec.Scope != nil && b.ko.Spec.Scope != nil {
		if *a.ko.Spec.Scope != *b.ko.Spec.Scope {
			delta.Add("Spec.Scope", a.ko.Spec.Scope, b.ko.Spec.Scope)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VisibilityConfig, b.ko.Spec.VisibilityConfig) {
		delta.Add("Spec.VisibilityConfig", a.ko.Spec.VisibilityConfig, b.ko.Spec.VisibilityConfig)
	} else if a.ko.Spec.VisibilityConfig != nil && b.ko.Spec.VisibilityConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled, b.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled) {
			delta.Add("Spec.VisibilityConfig.CloudWatchMetricsEnabled", a.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled, b.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled)
		} else if a.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled != nil && b.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled != nil {
			if *a.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled != *b.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled {
				delta.Add("Spec.VisibilityConfig.CloudWatchMetricsEnabled", a.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled, b.ko.Spec.VisibilityConfig.CloudWatchMetricsEnabled)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.VisibilityConfig.MetricName, b.ko.Spec.VisibilityConfig.MetricName) {
			delta.Add("Spec.VisibilityConfig.MetricName", a.ko.Spec.VisibilityConfig.MetricName, b.ko.Spec.VisibilityConfig.MetricName)
		} else if a.ko.Spec.VisibilityConfig.MetricName != nil && b.ko.Spec.VisibilityConfig.MetricName != nil {
			if *a.ko.Spec.VisibilityConfig.MetricName != *b.ko.Spec.VisibilityConfig.MetricName {
				delta.Add("Spec.VisibilityConfig.MetricName", a.ko.Spec.VisibilityConfig.MetricName, b.ko.Spec.VisibilityConfig.MetricName)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.VisibilityConfig.SampledRequestsEnabled, b.ko.Spec.VisibilityConfig.SampledRequestsEnabled) {
			delta.Add("Spec.VisibilityConfig.SampledRequestsEnabled", a.ko.Spec.VisibilityConfig.SampledRequestsEnabled, b.ko.Spec.VisibilityConfig.SampledRequestsEnabled)
		} else if a.ko.Spec.VisibilityConfig.SampledRequestsEnabled != nil && b.ko.Spec.VisibilityConfig.SampledRequestsEnabled != nil {
			if *a.ko.Spec.VisibilityConfig.SampledRequestsEnabled != *b.ko.Spec.VisibilityConfig.SampledRequestsEnabled {
				delta.Add("Spec.VisibilityConfig.SampledRequestsEnabled", a.ko.Spec.VisibilityConfig.SampledRequestsEnabled, b.ko.Spec.VisibilityConfig.SampledRequestsEnabled)
			}
		}
	}

	return delta
}
