# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS WAFV2 controller is a service controller for managing WAFV2 resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon WAFV2
description: |-
  Manage Amazon Web Application Firewall (Amazon WAFV2) resources in AWS from within your Kubernetes cluster.


  **About Amazon WAFV2**


  AWS WAF is a web application firewall that lets you monitor the HTTP and HTTPS requests that are forwarded to your protected web application resources. You can protect the following resource types:

  - Amazon CloudFront distribution

  - Amazon API Gateway REST API

  - Application Load Balancer

  - AWS AppSync GraphQL API

  - Amazon Cognito user pool

  - AWS App Runner service

  - AWS Verified Access instance


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: IPSet
  spec: '{}'
maintainers:
- name: "wafv2 maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon WAFV2 Developer Resources
  url: https://aws.amazon.com/waf/resources/
