// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ActionValue string

const (
	ActionValue_ALLOW             ActionValue = "ALLOW"
	ActionValue_BLOCK             ActionValue = "BLOCK"
	ActionValue_CAPTCHA           ActionValue = "CAPTCHA"
	ActionValue_CHALLENGE         ActionValue = "CHALLENGE"
	ActionValue_COUNT             ActionValue = "COUNT"
	ActionValue_EXCLUDED_AS_COUNT ActionValue = "EXCLUDED_AS_COUNT"
)

type AssociatedResourceType string

const (
	AssociatedResourceType_API_GATEWAY              AssociatedResourceType = "API_GATEWAY"
	AssociatedResourceType_APP_RUNNER_SERVICE       AssociatedResourceType = "APP_RUNNER_SERVICE"
	AssociatedResourceType_CLOUDFRONT               AssociatedResourceType = "CLOUDFRONT"
	AssociatedResourceType_COGNITO_USER_POOL        AssociatedResourceType = "COGNITO_USER_POOL"
	AssociatedResourceType_VERIFIED_ACCESS_INSTANCE AssociatedResourceType = "VERIFIED_ACCESS_INSTANCE"
)

type BodyParsingFallbackBehavior string

const (
	BodyParsingFallbackBehavior_EVALUATE_AS_STRING BodyParsingFallbackBehavior = "EVALUATE_AS_STRING"
	BodyParsingFallbackBehavior_MATCH              BodyParsingFallbackBehavior = "MATCH"
	BodyParsingFallbackBehavior_NO_MATCH           BodyParsingFallbackBehavior = "NO_MATCH"
)

type ComparisonOperator string

const (
	ComparisonOperator_EQ ComparisonOperator = "EQ"
	ComparisonOperator_GE ComparisonOperator = "GE"
	ComparisonOperator_GT ComparisonOperator = "GT"
	ComparisonOperator_LE ComparisonOperator = "LE"
	ComparisonOperator_LT ComparisonOperator = "LT"
	ComparisonOperator_NE ComparisonOperator = "NE"
)

type CountryCode string

const (
	CountryCode_AD CountryCode = "AD"
	CountryCode_AE CountryCode = "AE"
	CountryCode_AF CountryCode = "AF"
	CountryCode_AG CountryCode = "AG"
	CountryCode_AI CountryCode = "AI"
	CountryCode_AL CountryCode = "AL"
	CountryCode_AM CountryCode = "AM"
	CountryCode_AO CountryCode = "AO"
	CountryCode_AQ CountryCode = "AQ"
	CountryCode_AR CountryCode = "AR"
	CountryCode_AS CountryCode = "AS"
	CountryCode_AT CountryCode = "AT"
	CountryCode_AU CountryCode = "AU"
	CountryCode_AW CountryCode = "AW"
	CountryCode_AX CountryCode = "AX"
	CountryCode_AZ CountryCode = "AZ"
	CountryCode_BA CountryCode = "BA"
	CountryCode_BB CountryCode = "BB"
	CountryCode_BD CountryCode = "BD"
	CountryCode_BE CountryCode = "BE"
	CountryCode_BF CountryCode = "BF"
	CountryCode_BG CountryCode = "BG"
	CountryCode_BH CountryCode = "BH"
	CountryCode_BI CountryCode = "BI"
	CountryCode_BJ CountryCode = "BJ"
	CountryCode_BL CountryCode = "BL"
	CountryCode_BM CountryCode = "BM"
	CountryCode_BN CountryCode = "BN"
	CountryCode_BO CountryCode = "BO"
	CountryCode_BQ CountryCode = "BQ"
	CountryCode_BR CountryCode = "BR"
	CountryCode_BS CountryCode = "BS"
	CountryCode_BT CountryCode = "BT"
	CountryCode_BV CountryCode = "BV"
	CountryCode_BW CountryCode = "BW"
	CountryCode_BY CountryCode = "BY"
	CountryCode_BZ CountryCode = "BZ"
	CountryCode_CA CountryCode = "CA"
	CountryCode_CC CountryCode = "CC"
	CountryCode_CD CountryCode = "CD"
	CountryCode_CF CountryCode = "CF"
	CountryCode_CG CountryCode = "CG"
	CountryCode_CH CountryCode = "CH"
	CountryCode_CI CountryCode = "CI"
	CountryCode_CK CountryCode = "CK"
	CountryCode_CL CountryCode = "CL"
	CountryCode_CM CountryCode = "CM"
	CountryCode_CN CountryCode = "CN"
	CountryCode_CO CountryCode = "CO"
	CountryCode_CR CountryCode = "CR"
	CountryCode_CU CountryCode = "CU"
	CountryCode_CV CountryCode = "CV"
	CountryCode_CW CountryCode = "CW"
	CountryCode_CX CountryCode = "CX"
	CountryCode_CY CountryCode = "CY"
	CountryCode_CZ CountryCode = "CZ"
	CountryCode_DE CountryCode = "DE"
	CountryCode_DJ CountryCode = "DJ"
	CountryCode_DK CountryCode = "DK"
	CountryCode_DM CountryCode = "DM"
	CountryCode_DO CountryCode = "DO"
	CountryCode_DZ CountryCode = "DZ"
	CountryCode_EC CountryCode = "EC"
	CountryCode_EE CountryCode = "EE"
	CountryCode_EG CountryCode = "EG"
	CountryCode_EH CountryCode = "EH"
	CountryCode_ER CountryCode = "ER"
	CountryCode_ES CountryCode = "ES"
	CountryCode_ET CountryCode = "ET"
	CountryCode_FI CountryCode = "FI"
	CountryCode_FJ CountryCode = "FJ"
	CountryCode_FK CountryCode = "FK"
	CountryCode_FM CountryCode = "FM"
	CountryCode_FO CountryCode = "FO"
	CountryCode_FR CountryCode = "FR"
	CountryCode_GA CountryCode = "GA"
	CountryCode_GB CountryCode = "GB"
	CountryCode_GD CountryCode = "GD"
	CountryCode_GE CountryCode = "GE"
	CountryCode_GF CountryCode = "GF"
	CountryCode_GG CountryCode = "GG"
	CountryCode_GH CountryCode = "GH"
	CountryCode_GI CountryCode = "GI"
	CountryCode_GL CountryCode = "GL"
	CountryCode_GM CountryCode = "GM"
	CountryCode_GN CountryCode = "GN"
	CountryCode_GP CountryCode = "GP"
	CountryCode_GQ CountryCode = "GQ"
	CountryCode_GR CountryCode = "GR"
	CountryCode_GS CountryCode = "GS"
	CountryCode_GT CountryCode = "GT"
	CountryCode_GU CountryCode = "GU"
	CountryCode_GW CountryCode = "GW"
	CountryCode_GY CountryCode = "GY"
	CountryCode_HK CountryCode = "HK"
	CountryCode_HM CountryCode = "HM"
	CountryCode_HN CountryCode = "HN"
	CountryCode_HR CountryCode = "HR"
	CountryCode_HT CountryCode = "HT"
	CountryCode_HU CountryCode = "HU"
	CountryCode_ID CountryCode = "ID"
	CountryCode_IE CountryCode = "IE"
	CountryCode_IL CountryCode = "IL"
	CountryCode_IM CountryCode = "IM"
	CountryCode_IN CountryCode = "IN"
	CountryCode_IO CountryCode = "IO"
	CountryCode_IQ CountryCode = "IQ"
	CountryCode_IR CountryCode = "IR"
	CountryCode_IS CountryCode = "IS"
	CountryCode_IT CountryCode = "IT"
	CountryCode_JE CountryCode = "JE"
	CountryCode_JM CountryCode = "JM"
	CountryCode_JO CountryCode = "JO"
	CountryCode_JP CountryCode = "JP"
	CountryCode_KE CountryCode = "KE"
	CountryCode_KG CountryCode = "KG"
	CountryCode_KH CountryCode = "KH"
	CountryCode_KI CountryCode = "KI"
	CountryCode_KM CountryCode = "KM"
	CountryCode_KN CountryCode = "KN"
	CountryCode_KP CountryCode = "KP"
	CountryCode_KR CountryCode = "KR"
	CountryCode_KW CountryCode = "KW"
	CountryCode_KY CountryCode = "KY"
	CountryCode_KZ CountryCode = "KZ"
	CountryCode_LA CountryCode = "LA"
	CountryCode_LB CountryCode = "LB"
	CountryCode_LC CountryCode = "LC"
	CountryCode_LI CountryCode = "LI"
	CountryCode_LK CountryCode = "LK"
	CountryCode_LR CountryCode = "LR"
	CountryCode_LS CountryCode = "LS"
	CountryCode_LT CountryCode = "LT"
	CountryCode_LU CountryCode = "LU"
	CountryCode_LV CountryCode = "LV"
	CountryCode_LY CountryCode = "LY"
	CountryCode_MA CountryCode = "MA"
	CountryCode_MC CountryCode = "MC"
	CountryCode_MD CountryCode = "MD"
	CountryCode_ME CountryCode = "ME"
	CountryCode_MF CountryCode = "MF"
	CountryCode_MG CountryCode = "MG"
	CountryCode_MH CountryCode = "MH"
	CountryCode_MK CountryCode = "MK"
	CountryCode_ML CountryCode = "ML"
	CountryCode_MM CountryCode = "MM"
	CountryCode_MN CountryCode = "MN"
	CountryCode_MO CountryCode = "MO"
	CountryCode_MP CountryCode = "MP"
	CountryCode_MQ CountryCode = "MQ"
	CountryCode_MR CountryCode = "MR"
	CountryCode_MS CountryCode = "MS"
	CountryCode_MT CountryCode = "MT"
	CountryCode_MU CountryCode = "MU"
	CountryCode_MV CountryCode = "MV"
	CountryCode_MW CountryCode = "MW"
	CountryCode_MX CountryCode = "MX"
	CountryCode_MY CountryCode = "MY"
	CountryCode_MZ CountryCode = "MZ"
	CountryCode_NA CountryCode = "NA"
	CountryCode_NC CountryCode = "NC"
	CountryCode_NE CountryCode = "NE"
	CountryCode_NF CountryCode = "NF"
	CountryCode_NG CountryCode = "NG"
	CountryCode_NI CountryCode = "NI"
	CountryCode_NL CountryCode = "NL"
	CountryCode_NO CountryCode = "NO"
	CountryCode_NP CountryCode = "NP"
	CountryCode_NR CountryCode = "NR"
	CountryCode_NU CountryCode = "NU"
	CountryCode_NZ CountryCode = "NZ"
	CountryCode_OM CountryCode = "OM"
	CountryCode_PA CountryCode = "PA"
	CountryCode_PE CountryCode = "PE"
	CountryCode_PF CountryCode = "PF"
	CountryCode_PG CountryCode = "PG"
	CountryCode_PH CountryCode = "PH"
	CountryCode_PK CountryCode = "PK"
	CountryCode_PL CountryCode = "PL"
	CountryCode_PM CountryCode = "PM"
	CountryCode_PN CountryCode = "PN"
	CountryCode_PR CountryCode = "PR"
	CountryCode_PS CountryCode = "PS"
	CountryCode_PT CountryCode = "PT"
	CountryCode_PW CountryCode = "PW"
	CountryCode_PY CountryCode = "PY"
	CountryCode_QA CountryCode = "QA"
	CountryCode_RE CountryCode = "RE"
	CountryCode_RO CountryCode = "RO"
	CountryCode_RS CountryCode = "RS"
	CountryCode_RU CountryCode = "RU"
	CountryCode_RW CountryCode = "RW"
	CountryCode_SA CountryCode = "SA"
	CountryCode_SB CountryCode = "SB"
	CountryCode_SC CountryCode = "SC"
	CountryCode_SD CountryCode = "SD"
	CountryCode_SE CountryCode = "SE"
	CountryCode_SG CountryCode = "SG"
	CountryCode_SH CountryCode = "SH"
	CountryCode_SI CountryCode = "SI"
	CountryCode_SJ CountryCode = "SJ"
	CountryCode_SK CountryCode = "SK"
	CountryCode_SL CountryCode = "SL"
	CountryCode_SM CountryCode = "SM"
	CountryCode_SN CountryCode = "SN"
	CountryCode_SO CountryCode = "SO"
	CountryCode_SR CountryCode = "SR"
	CountryCode_SS CountryCode = "SS"
	CountryCode_ST CountryCode = "ST"
	CountryCode_SV CountryCode = "SV"
	CountryCode_SX CountryCode = "SX"
	CountryCode_SY CountryCode = "SY"
	CountryCode_SZ CountryCode = "SZ"
	CountryCode_TC CountryCode = "TC"
	CountryCode_TD CountryCode = "TD"
	CountryCode_TF CountryCode = "TF"
	CountryCode_TG CountryCode = "TG"
	CountryCode_TH CountryCode = "TH"
	CountryCode_TJ CountryCode = "TJ"
	CountryCode_TK CountryCode = "TK"
	CountryCode_TL CountryCode = "TL"
	CountryCode_TM CountryCode = "TM"
	CountryCode_TN CountryCode = "TN"
	CountryCode_TO CountryCode = "TO"
	CountryCode_TR CountryCode = "TR"
	CountryCode_TT CountryCode = "TT"
	CountryCode_TV CountryCode = "TV"
	CountryCode_TW CountryCode = "TW"
	CountryCode_TZ CountryCode = "TZ"
	CountryCode_UA CountryCode = "UA"
	CountryCode_UG CountryCode = "UG"
	CountryCode_UM CountryCode = "UM"
	CountryCode_US CountryCode = "US"
	CountryCode_UY CountryCode = "UY"
	CountryCode_UZ CountryCode = "UZ"
	CountryCode_VA CountryCode = "VA"
	CountryCode_VC CountryCode = "VC"
	CountryCode_VE CountryCode = "VE"
	CountryCode_VG CountryCode = "VG"
	CountryCode_VI CountryCode = "VI"
	CountryCode_VN CountryCode = "VN"
	CountryCode_VU CountryCode = "VU"
	CountryCode_WF CountryCode = "WF"
	CountryCode_WS CountryCode = "WS"
	CountryCode_XK CountryCode = "XK"
	CountryCode_YE CountryCode = "YE"
	CountryCode_YT CountryCode = "YT"
	CountryCode_ZA CountryCode = "ZA"
	CountryCode_ZM CountryCode = "ZM"
	CountryCode_ZW CountryCode = "ZW"
)

type FailureReason string

const (
	FailureReason_TOKEN_DOMAIN_MISMATCH FailureReason = "TOKEN_DOMAIN_MISMATCH"
	FailureReason_TOKEN_EXPIRED         FailureReason = "TOKEN_EXPIRED"
	FailureReason_TOKEN_INVALID         FailureReason = "TOKEN_INVALID"
	FailureReason_TOKEN_MISSING         FailureReason = "TOKEN_MISSING"
)

type FallbackBehavior string

const (
	FallbackBehavior_MATCH    FallbackBehavior = "MATCH"
	FallbackBehavior_NO_MATCH FallbackBehavior = "NO_MATCH"
)

type FilterBehavior string

const (
	FilterBehavior_DROP FilterBehavior = "DROP"
	FilterBehavior_KEEP FilterBehavior = "KEEP"
)

type FilterRequirement string

const (
	FilterRequirement_MEETS_ALL FilterRequirement = "MEETS_ALL"
	FilterRequirement_MEETS_ANY FilterRequirement = "MEETS_ANY"
)

type ForwardedIPPosition string

const (
	ForwardedIPPosition_ANY   ForwardedIPPosition = "ANY"
	ForwardedIPPosition_FIRST ForwardedIPPosition = "FIRST"
	ForwardedIPPosition_LAST  ForwardedIPPosition = "LAST"
)

type IPAddressVersion string

const (
	IPAddressVersion_IPV4 IPAddressVersion = "IPV4"
	IPAddressVersion_IPV6 IPAddressVersion = "IPV6"
)

type InspectionLevel string

const (
	InspectionLevel_COMMON   InspectionLevel = "COMMON"
	InspectionLevel_TARGETED InspectionLevel = "TARGETED"
)

type JSONMatchScope string

const (
	JSONMatchScope_ALL   JSONMatchScope = "ALL"
	JSONMatchScope_KEY   JSONMatchScope = "KEY"
	JSONMatchScope_VALUE JSONMatchScope = "VALUE"
)

type LabelMatchScope string

const (
	LabelMatchScope_LABEL     LabelMatchScope = "LABEL"
	LabelMatchScope_NAMESPACE LabelMatchScope = "NAMESPACE"
)

type LogScope string

const (
	LogScope_CUSTOMER      LogScope = "CUSTOMER"
	LogScope_SECURITY_LAKE LogScope = "SECURITY_LAKE"
)

type LogType string

const (
	LogType_WAF_LOGS LogType = "WAF_LOGS"
)

type MapMatchScope string

const (
	MapMatchScope_ALL   MapMatchScope = "ALL"
	MapMatchScope_KEY   MapMatchScope = "KEY"
	MapMatchScope_VALUE MapMatchScope = "VALUE"
)

type OversizeHandling string

const (
	OversizeHandling_CONTINUE OversizeHandling = "CONTINUE"
	OversizeHandling_MATCH    OversizeHandling = "MATCH"
	OversizeHandling_NO_MATCH OversizeHandling = "NO_MATCH"
)

type ParameterExceptionField string

const (
	ParameterExceptionField_ACP_RULE_SET_RESPONSE_INSPECTION  ParameterExceptionField = "ACP_RULE_SET_RESPONSE_INSPECTION"
	ParameterExceptionField_AND_STATEMENT                     ParameterExceptionField = "AND_STATEMENT"
	ParameterExceptionField_ASSOCIABLE_RESOURCE               ParameterExceptionField = "ASSOCIABLE_RESOURCE"
	ParameterExceptionField_ASSOCIATED_RESOURCE_TYPE          ParameterExceptionField = "ASSOCIATED_RESOURCE_TYPE"
	ParameterExceptionField_ATP_RULE_SET_RESPONSE_INSPECTION  ParameterExceptionField = "ATP_RULE_SET_RESPONSE_INSPECTION"
	ParameterExceptionField_BODY_PARSING_FALLBACK_BEHAVIOR    ParameterExceptionField = "BODY_PARSING_FALLBACK_BEHAVIOR"
	ParameterExceptionField_BYTE_MATCH_STATEMENT              ParameterExceptionField = "BYTE_MATCH_STATEMENT"
	ParameterExceptionField_CHALLENGE_CONFIG                  ParameterExceptionField = "CHALLENGE_CONFIG"
	ParameterExceptionField_CHANGE_PROPAGATION_STATUS         ParameterExceptionField = "CHANGE_PROPAGATION_STATUS"
	ParameterExceptionField_COOKIE_MATCH_PATTERN              ParameterExceptionField = "COOKIE_MATCH_PATTERN"
	ParameterExceptionField_CUSTOM_KEYS                       ParameterExceptionField = "CUSTOM_KEYS"
	ParameterExceptionField_CUSTOM_REQUEST_HANDLING           ParameterExceptionField = "CUSTOM_REQUEST_HANDLING"
	ParameterExceptionField_CUSTOM_RESPONSE                   ParameterExceptionField = "CUSTOM_RESPONSE"
	ParameterExceptionField_CUSTOM_RESPONSE_BODY              ParameterExceptionField = "CUSTOM_RESPONSE_BODY"
	ParameterExceptionField_DEFAULT_ACTION                    ParameterExceptionField = "DEFAULT_ACTION"
	ParameterExceptionField_ENTITY_LIMIT                      ParameterExceptionField = "ENTITY_LIMIT"
	ParameterExceptionField_EXCLUDED_RULE                     ParameterExceptionField = "EXCLUDED_RULE"
	ParameterExceptionField_EXPIRE_TIMESTAMP                  ParameterExceptionField = "EXPIRE_TIMESTAMP"
	ParameterExceptionField_FALLBACK_BEHAVIOR                 ParameterExceptionField = "FALLBACK_BEHAVIOR"
	ParameterExceptionField_FIELD_TO_MATCH                    ParameterExceptionField = "FIELD_TO_MATCH"
	ParameterExceptionField_FILTER_CONDITION                  ParameterExceptionField = "FILTER_CONDITION"
	ParameterExceptionField_FIREWALL_MANAGER_STATEMENT        ParameterExceptionField = "FIREWALL_MANAGER_STATEMENT"
	ParameterExceptionField_FORWARDED_IP_CONFIG               ParameterExceptionField = "FORWARDED_IP_CONFIG"
	ParameterExceptionField_GEO_MATCH_STATEMENT               ParameterExceptionField = "GEO_MATCH_STATEMENT"
	ParameterExceptionField_HEADER_MATCH_PATTERN              ParameterExceptionField = "HEADER_MATCH_PATTERN"
	ParameterExceptionField_HEADER_NAME                       ParameterExceptionField = "HEADER_NAME"
	ParameterExceptionField_IP_ADDRESS                        ParameterExceptionField = "IP_ADDRESS"
	ParameterExceptionField_IP_ADDRESS_VERSION                ParameterExceptionField = "IP_ADDRESS_VERSION"
	ParameterExceptionField_IP_SET                            ParameterExceptionField = "IP_SET"
	ParameterExceptionField_IP_SET_FORWARDED_IP_CONFIG        ParameterExceptionField = "IP_SET_FORWARDED_IP_CONFIG"
	ParameterExceptionField_IP_SET_REFERENCE_STATEMENT        ParameterExceptionField = "IP_SET_REFERENCE_STATEMENT"
	ParameterExceptionField_JSON_MATCH_PATTERN                ParameterExceptionField = "JSON_MATCH_PATTERN"
	ParameterExceptionField_JSON_MATCH_SCOPE                  ParameterExceptionField = "JSON_MATCH_SCOPE"
	ParameterExceptionField_LABEL_MATCH_STATEMENT             ParameterExceptionField = "LABEL_MATCH_STATEMENT"
	ParameterExceptionField_LOGGING_FILTER                    ParameterExceptionField = "LOGGING_FILTER"
	ParameterExceptionField_LOG_DESTINATION                   ParameterExceptionField = "LOG_DESTINATION"
	ParameterExceptionField_MANAGED_RULE_GROUP_CONFIG         ParameterExceptionField = "MANAGED_RULE_GROUP_CONFIG"
	ParameterExceptionField_MANAGED_RULE_SET                  ParameterExceptionField = "MANAGED_RULE_SET"
	ParameterExceptionField_MANAGED_RULE_SET_STATEMENT        ParameterExceptionField = "MANAGED_RULE_SET_STATEMENT"
	ParameterExceptionField_MAP_MATCH_SCOPE                   ParameterExceptionField = "MAP_MATCH_SCOPE"
	ParameterExceptionField_METRIC_NAME                       ParameterExceptionField = "METRIC_NAME"
	ParameterExceptionField_NOT_STATEMENT                     ParameterExceptionField = "NOT_STATEMENT"
	ParameterExceptionField_OR_STATEMENT                      ParameterExceptionField = "OR_STATEMENT"
	ParameterExceptionField_OVERRIDE_ACTION                   ParameterExceptionField = "OVERRIDE_ACTION"
	ParameterExceptionField_OVERSIZE_HANDLING                 ParameterExceptionField = "OVERSIZE_HANDLING"
	ParameterExceptionField_PAYLOAD_TYPE                      ParameterExceptionField = "PAYLOAD_TYPE"
	ParameterExceptionField_POSITION                          ParameterExceptionField = "POSITION"
	ParameterExceptionField_RATE_BASED_STATEMENT              ParameterExceptionField = "RATE_BASED_STATEMENT"
	ParameterExceptionField_REGEX_PATTERN_REFERENCE_STATEMENT ParameterExceptionField = "REGEX_PATTERN_REFERENCE_STATEMENT"
	ParameterExceptionField_REGEX_PATTERN_SET                 ParameterExceptionField = "REGEX_PATTERN_SET"
	ParameterExceptionField_RESOURCE_ARN                      ParameterExceptionField = "RESOURCE_ARN"
	ParameterExceptionField_RESOURCE_TYPE                     ParameterExceptionField = "RESOURCE_TYPE"
	ParameterExceptionField_RESPONSE_CONTENT_TYPE             ParameterExceptionField = "RESPONSE_CONTENT_TYPE"
	ParameterExceptionField_RULE                              ParameterExceptionField = "RULE"
	ParameterExceptionField_RULE_ACTION                       ParameterExceptionField = "RULE_ACTION"
	ParameterExceptionField_RULE_GROUP                        ParameterExceptionField = "RULE_GROUP"
	ParameterExceptionField_RULE_GROUP_REFERENCE_STATEMENT    ParameterExceptionField = "RULE_GROUP_REFERENCE_STATEMENT"
	ParameterExceptionField_SCOPE_DOWN                        ParameterExceptionField = "SCOPE_DOWN"
	ParameterExceptionField_SCOPE_VALUE                       ParameterExceptionField = "SCOPE_VALUE"
	ParameterExceptionField_SINGLE_HEADER                     ParameterExceptionField = "SINGLE_HEADER"
	ParameterExceptionField_SINGLE_QUERY_ARGUMENT             ParameterExceptionField = "SINGLE_QUERY_ARGUMENT"
	ParameterExceptionField_SIZE_CONSTRAINT_STATEMENT         ParameterExceptionField = "SIZE_CONSTRAINT_STATEMENT"
	ParameterExceptionField_SQLI_MATCH_STATEMENT              ParameterExceptionField = "SQLI_MATCH_STATEMENT"
	ParameterExceptionField_STATEMENT                         ParameterExceptionField = "STATEMENT"
	ParameterExceptionField_TAGS                              ParameterExceptionField = "TAGS"
	ParameterExceptionField_TAG_KEYS                          ParameterExceptionField = "TAG_KEYS"
	ParameterExceptionField_TEXT_TRANSFORMATION               ParameterExceptionField = "TEXT_TRANSFORMATION"
	ParameterExceptionField_TOKEN_DOMAIN                      ParameterExceptionField = "TOKEN_DOMAIN"
	ParameterExceptionField_WEB_ACL                           ParameterExceptionField = "WEB_ACL"
	ParameterExceptionField_XSS_MATCH_STATEMENT               ParameterExceptionField = "XSS_MATCH_STATEMENT"
)

type PayloadType string

const (
	PayloadType_FORM_ENCODED PayloadType = "FORM_ENCODED"
	PayloadType_JSON         PayloadType = "JSON"
)

type Platform string

const (
	Platform_ANDROID Platform = "ANDROID"
	Platform_IOS     Platform = "IOS"
)

type PositionalConstraint string

const (
	PositionalConstraint_CONTAINS      PositionalConstraint = "CONTAINS"
	PositionalConstraint_CONTAINS_WORD PositionalConstraint = "CONTAINS_WORD"
	PositionalConstraint_ENDS_WITH     PositionalConstraint = "ENDS_WITH"
	PositionalConstraint_EXACTLY       PositionalConstraint = "EXACTLY"
	PositionalConstraint_STARTS_WITH   PositionalConstraint = "STARTS_WITH"
)

type RateBasedStatementAggregateKeyType string

const (
	RateBasedStatementAggregateKeyType_CONSTANT     RateBasedStatementAggregateKeyType = "CONSTANT"
	RateBasedStatementAggregateKeyType_CUSTOM_KEYS  RateBasedStatementAggregateKeyType = "CUSTOM_KEYS"
	RateBasedStatementAggregateKeyType_FORWARDED_IP RateBasedStatementAggregateKeyType = "FORWARDED_IP"
	RateBasedStatementAggregateKeyType_IP           RateBasedStatementAggregateKeyType = "IP"
)

type ResourceType string

const (
	ResourceType_API_GATEWAY               ResourceType = "API_GATEWAY"
	ResourceType_APPLICATION_LOAD_BALANCER ResourceType = "APPLICATION_LOAD_BALANCER"
	ResourceType_APPSYNC                   ResourceType = "APPSYNC"
	ResourceType_APP_RUNNER_SERVICE        ResourceType = "APP_RUNNER_SERVICE"
	ResourceType_COGNITO_USER_POOL         ResourceType = "COGNITO_USER_POOL"
	ResourceType_VERIFIED_ACCESS_INSTANCE  ResourceType = "VERIFIED_ACCESS_INSTANCE"
)

type ResponseContentType string

const (
	ResponseContentType_APPLICATION_JSON ResponseContentType = "APPLICATION_JSON"
	ResponseContentType_TEXT_HTML        ResponseContentType = "TEXT_HTML"
	ResponseContentType_TEXT_PLAIN       ResponseContentType = "TEXT_PLAIN"
)

type Scope string

const (
	Scope_CLOUDFRONT Scope = "CLOUDFRONT"
	Scope_REGIONAL   Scope = "REGIONAL"
)

type SensitivityLevel string

const (
	SensitivityLevel_HIGH SensitivityLevel = "HIGH"
	SensitivityLevel_LOW  SensitivityLevel = "LOW"
)

type SizeInspectionLimit string

const (
	SizeInspectionLimit_KB_16 SizeInspectionLimit = "KB_16"
	SizeInspectionLimit_KB_32 SizeInspectionLimit = "KB_32"
	SizeInspectionLimit_KB_48 SizeInspectionLimit = "KB_48"
	SizeInspectionLimit_KB_64 SizeInspectionLimit = "KB_64"
)

type TextTransformationType string

const (
	TextTransformationType_BASE64_DECODE        TextTransformationType = "BASE64_DECODE"
	TextTransformationType_BASE64_DECODE_EXT    TextTransformationType = "BASE64_DECODE_EXT"
	TextTransformationType_CMD_LINE             TextTransformationType = "CMD_LINE"
	TextTransformationType_COMPRESS_WHITE_SPACE TextTransformationType = "COMPRESS_WHITE_SPACE"
	TextTransformationType_CSS_DECODE           TextTransformationType = "CSS_DECODE"
	TextTransformationType_ESCAPE_SEQ_DECODE    TextTransformationType = "ESCAPE_SEQ_DECODE"
	TextTransformationType_HEX_DECODE           TextTransformationType = "HEX_DECODE"
	TextTransformationType_HTML_ENTITY_DECODE   TextTransformationType = "HTML_ENTITY_DECODE"
	TextTransformationType_JS_DECODE            TextTransformationType = "JS_DECODE"
	TextTransformationType_LOWERCASE            TextTransformationType = "LOWERCASE"
	TextTransformationType_MD5                  TextTransformationType = "MD5"
	TextTransformationType_NONE                 TextTransformationType = "NONE"
	TextTransformationType_NORMALIZE_PATH       TextTransformationType = "NORMALIZE_PATH"
	TextTransformationType_NORMALIZE_PATH_WIN   TextTransformationType = "NORMALIZE_PATH_WIN"
	TextTransformationType_REMOVE_NULLS         TextTransformationType = "REMOVE_NULLS"
	TextTransformationType_REPLACE_COMMENTS     TextTransformationType = "REPLACE_COMMENTS"
	TextTransformationType_REPLACE_NULLS        TextTransformationType = "REPLACE_NULLS"
	TextTransformationType_SQL_HEX_DECODE       TextTransformationType = "SQL_HEX_DECODE"
	TextTransformationType_URL_DECODE           TextTransformationType = "URL_DECODE"
	TextTransformationType_URL_DECODE_UNI       TextTransformationType = "URL_DECODE_UNI"
	TextTransformationType_UTF8_TO_UNICODE      TextTransformationType = "UTF8_TO_UNICODE"
)
